M48
; DRILL file KiCad 10.0.6 date 2026-09-28T20:09:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T20:09:04-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X6.355Y-156.86
X6.355Y-162.64
T2
X6.65Y-186.19
X6.65Y-197.62
M30
